apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-client
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/portforward"]
  verbs: ["get", "list", "create"]
