apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: hello-world.ajs
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-service
                port:
                  number: 80
    - host: devops.ajs
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-service
                port:
                  number: 80
