kind: Service
apiVersion: v1
metadata:
  name: devops-service
spec:
  # type: NodePort
  selector:
    app: devops-303
  ports:
    - protocol: TCP
      port: 8884
      targetPort: 8884
      # nodePort: 30036
