kind: Service
apiVersion: v1
metadata:
  name: hello-service
spec:
  # type: NodePort
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: 30036